run_type = "sampling"
json_config = "~/REINVENT4/exps/sampling.json"
output_csv = "~/REINVENT4/exps/sampling.csv"

[logging]
console = true
file = true

[parameters.specific]
model_path = "priors/reinvent.prior"
number_of_molecules = 1000
unique_molecules = true
randomize = true
